interface UnsplashImageData {
    id: string,
    created_at: string,
    updated_at: string,
    width: number,
    height: number,
    color: string,
    description: string | null,
    urls: {
        raw: string,
        full: string,
        regular: string,
        small: string,
        thumb: string,
    },
    links: {
        self: string,
        html: string,
        download: string,
        download_location: string,
    },
    categories: Array<any>,
    sponsored: boolean,
    sponsored_by: string | null,
    sponsored_impressions_id: string | null,
    likes: number,
    liked_by_user: boolean,
    current_user_collections: Array<any>,
    slug: null | string,
    user: any,
}